name: CI
on: [pull_request]
jobs:
  lint_and_test:

    name: Lint and Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Commit lint
        uses: wagoid/commitlint-github-action@v2
        env:
          CI: true

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Code lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          KLARNA_USERNAME: ${{ secrets.KLARNA_USERNAME }}
          KLARNA_PASSWORD: ${{ secrets.KLARNA_PASSWORD }}
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

